name: Publish to PyPI

# Trigger: only when a tag starting with 'v' is pushed to the repository
# For example: git push origin v0.1.0 (will trigger)
on:
  push:
    tags:
      - "v*"

jobs:
  # First stage: test and build
  # This step is to ensure the code is notÁÉÇ, and can successfullyÊâìÂá∫ÂåÖÊù•
  build-n-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Use your base version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest
          pip install .

      - name: Run Tests
        # If tests fail, the process will stop here and not execute the subsequent package publishing
        run: |
          pytest tests/

      - name: Build package
        # Try to build, ensure MANIFEST.in is configured correctly, and no wrong files are included
        run: |
          python -m build

      # Store the built dist/ folder and pass it to the next job
      - name: Store distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  # Second stage: publish to PyPI
  # Only run if the build-n-test stage succeeds
  publish-to-pypi:
    name: Publish to PyPI
    needs: build-n-test # Dependency: must wait for tests to pass
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/puzzlekit
    permissions:
      id-token: write # This line is important for new Trusted Publishing, but also compatible with Token method

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution üì¶ to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
